### ISSUE TITLE
Peer-review - week #5

### ISSUE THREAD

**Issue by heidi-holappa** [oskrsjlnd/RSA-crypto#1]
# Peer-review
Time of testing: June 9th 18:30-22:11

## Topic 
RSA cryptosystem is a topic I am fairly unfamiliar with and I had to look into it a bit before diving into the peer review. Highly fascinating! 

Perhaps the design document could have a brief introduction to the subject so that someone who is unfamiliar with the topic would have easier time to dive in? My own project is lacking a similar feature and I will add some introductory explanation to my documentation, so this was a good learning experience! 

## Code quality
The code written so far was very clear and methods were well named, which made getting familiar with the code easier. I do think docstring would've been helpful for getting familiar with the functionalities and their relations. I was not yet familiar with operators such as '>>=' (bit shift) and '^' (bitwise XOR) in python and for example a short summary of the functionalities of the method could provide some hints on what to read on if the operators are unfamiliar and a basic understanding of the functionality even when some operators are unfamiliar, especially with a challenging topic such as this! 

Regarding the method with bit manipulation (exponent_for_prime_test): Since the topic was so new to me, evaluating the efficiency and usefulness of bit manipulation vs. manipulation of natural number with Python was something I did not have the experience/expertise for to comment on. It is my understanding that in some languages bit operations are more efficient, but I do not know if that applies for Python as well. Perhaps this could be addressed in some part of documentation as I assume using bit operations was a conscious choice.

I did a bit of testing on the  method 'generate_prime' with the following code. The new attribute self.falses_when_true was a simple counter that kept count of how many times method 'prime_test_round' returned false before a prime was found: 

```python
    for i in range(10):
        k = KeyGenerator()
        k.find_distinct_primes()
        print(k.falses_when_true)
```
For one run of the code I got these results (counters for the pair of primes created):
```
[4360, 1000]
[2880, 1840]
[10560, 2440]
[14904, 28668]
[6262, 8519]
[22800, 2520]
[840, 12840]
[10800, 2160]
[1320, 7480]
[13120, 12380]
```
It seems that there is quite a bit of fluctuation in the iterations this method has to go through? Perhaps this is part of the necessary process? With limited understanding to the topic at hand it came to my mind that is this something that could be optimized? 

The functionality of this segment I did not fully understand:
```python3
x = pow(a, d, prime_candidate)
if x in (1, prime_candidate - 1):
    return True
```
If I understood it correctly the idea is that x is the value of 'a to the power of d modulo prime_candidate'. To me it was unclear to me how this test (with the values generated by the method exponent_for_prime_test are enough to validate that the given value is a prime value. Would the only conditions in which this fails be if x == prime_candidate or if x == 0? And in these cases the following heavier iteration would be gone through to validate the proposed value? Perhaps this could be clarified to an unfamiliar reader with some docstring? 

## UI or other interaction with the application
Some form of implementation which allows user to test the functionality of this application could be useful. For this review I  wrote some code to test out the different methods to get a better understanding of their operations. In the design document's chapter "Input" a system to encrypt and decrypt messages was mentioned. This was still to be implemented at the time of testing, but would be a very useful feature, I think!  

## Tests
The tests seemed well thought out and tested the class in diversive ways. All tests passed and when I changed the parameters of some of the tests, it had an effect on test results. At the moment there were no tests for efficiency. Perhaps these could be included? 

## Scope
I am a bit concerned if your project is as far along as it perhaps should be at this time. The main functionality seems to be a good complete structure, but perhaps some features (like some sort of implementation for user interface) are still missing? But I assume this is something the course assistant will give feedback on, if needed, so it is not my place to evaluate this. The subject and content is, to me at least, very complex, so perhaps my concern is unfounded and everything is as it should be. And I also imagine that quality trumps quantity any time! 

## Other
For this course this is perhaps unimportant, but I learned in my last coding course (OHTE) that using getters and setters is considered unpythonic. If I understood correctly using property (decorators) is the more 'pythonic' way. Just mentioning this because I noticed the getters and thought this might be something you might be interested in looking into! 

## Summary of suggestions
* The user input implementation (UI or some other solution) was not included at the time of testing. This would be very useful feature for trying out the application. 
* Consider testing efficiency of algorithms in some way
* The peer review guidelines stated that documentation does not need to be commented, but here are two hopefully useful comments:
  * Execution report is missing (totetusraportti), this was on week #4 task list. 
  * Docstring (or other similar documentation/notation in code) is missing. To my understanding this is required for this course and it could be very helpful for review purposes. 

## Forewords
All in all diving into your project was very fascinating and I learned a lot and got helpful/useful ideas for my own project as well. I hope this feedback has some useful input for the rest of your project. Best of luck with the course and warm summer days!

**Comment by oskrsjlnd** [comment]
Thanks for the valuable feedback! For your question on the generate_prime() method it is actually not guaranteed to stop so that is why the fluctuation exists since it actually randomly picks numbers in the desired bit range, after which it actually runs the tests for said number so there is no guarantee that a prime number will be picked on the first couple of tries. It could actually very well run while testing hundreds of different numbers to see if they are prime.
